# Change these first
owner: nexmoe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nexmoe - Space
    url: https://i.nexmoe.com
  - name: Nexmoe - Blog
    url: https://nexmoe.com
  - name: Shu - Appwrite
    url: https://aw.xiaoshuapp.com
  - name: Shu - Homepage
    url: https://xiaoshuapp.com
  - name: Shu - Lib
    url: https://lib.xiaoshuapp.com
  - name: Shu - Web
    url: https://pro.xiaoshuapp.com
  - name: RoamingCloud
    url: https://roam.mixcm.com
  - name: BoTab - Homepage
    url: https://botab.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: nexmoe.github.io
  baseUrl: /upptime/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nexmoe Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
